### PR TITLE
Fix auth resolve #12

### LINKED ISSUE #12: Could not load companies
After install I get this message " Could not load companies"...and cannot create neither.
https://ibb.co/ZczgCs5

### PR DESCRIPTION
**Pull request by Daniyal-Javani**

### CODE REVIEW

**Review by PovilasKorop — COMMENTED** [review]
@Daniyal-Javani thank you for submitting the fix, but can't accept it with `composer.lock` file modified, cause I have no idea what versions of packages you have there. Did you just run `composer update` locally, or did you do something more than that?

**Comment by Daniyal-Javani** [comment]
@PovilasKorop I just run `composer update`, I don't know why but it didn't work without it.

**Comment by PovilasKorop** [comment]
@Daniyal-Javani yeah, but still I can't accept that pull request. I will manually edit readme with your suggestion, thanks.

**Comment by Daniyal-Javani** [comment]
@PovilasKorop but still, it will not work, maybe we should add `composer update` to readme.

**Pull request closed without merging**
